---
abstract: 'Perlish OO bindings to the L<Global Names Resolver|http://resolver.globalnames.org/> API'
author:
  - 'Dimitrios - Georgios Kontopoulos <d.kontopoulos13@imperial.ac.uk>'
build_requires:
  Test::Exception: 0
  Test::More: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-Taxonomy-GlobalNames
no_index:
  directory:
    - t
    - inc
requires:
  JSON: 2.9
  JSON::Parse: 0.23
  Moo: 1.003001
  REST::Client: 249
  perl: 5.006
resources:
  repository: https://github.com/dgkontopoulos/Bio-Taxonomy-GlobalNames.git
version: 0.01
