---
abstract: 'Perlish OO bindings to the L<Global Names Resolver|http://resolver.globalnames.org/> API'
author:
  - 'Dimitrios - Georgios Kontopoulos <d.kontopoulos13@imperial.ac.uk>'
build_requires:
  LWP::UserAgent: 6.05
  Test::Exception: 0
  Test::More: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-Taxonomy-GlobalNames
no_index:
  directory:
    - t
    - inc
requires:
  JSON: 2.9
  JSON::Parse: 0.23
  LWP::UserAgent: 6.05
  Moo::Lax: 0.12
  REST::Client: 249
  Scalar::Readonly: 0.03
  perl: 0
resources:
  repository: https://github.com/dgkontopoulos/Bio-Taxonomy-GlobalNames.git
version: 0.05
